name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run simple test
        run: |
          echo "✅ Tests passed!"
          echo "Test completed at $(date)"

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create build
        run: |
          mkdir -p dist
          echo "Built application" > dist/app.txt
          echo "✅ Build completed!"

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: staging
    steps:
      - name: Simulate deployment
        run: |
          echo "🚀 Deploying to staging..."
          echo "✅ Deployment successful!"
