name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Test passed"
  
  build:
    runs-on: ubuntu-latest  
    needs: test
    steps:
      - run: echo "✅ Build completed"
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "✅ Deployed"
